name: r_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - anyio=4.10.0=py39haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py39h02ab6af_0
  - asttokens=3.0.0=py39haa95532_0
  - async-lru=2.0.5=py39haa95532_0
  - attrs=25.4.0=py39haa95532_1
  - babel=2.16.0=py39haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_1
  - beautifulsoup4=4.13.5=py39haa95532_0
  - binutils_impl_win-64=2.45=default_ha84baeb_105
  - bleach=6.2.0=py39haa95532_0
  - brotlicffi=1.0.9.2=py39h885b0b7_2
  - bwidget=1.10.1=h57928b3_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.10.5=py39haa95532_0
  - cffi=2.0.0=py39h02ab6af_0
  - charset-normalizer=3.4.4=py39haa95532_0
  - colorama=0.4.6=py39haa95532_0
  - comm=0.2.1=py39haa95532_0
  - curl=8.18.0=h43ecb02_0
  - debugpy=1.8.16=py39h885b0b7_0
  - decorator=5.2.1=py39haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.3.0=py39haa95532_0
  - executing=2.2.1=py39haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=h57928b3_0
  - gcc_impl_win-64=15.2.0=h79c4613_16
  - gfortran_impl_win-64=15.2.0=h0e079bb_16
  - gsl=2.7=hdfb1a43_0
  - gxx_impl_win-64=15.2.0=h22fd5bf_16
  - h11=0.16.0=py39haa95532_0
  - httpcore=1.0.9=py39haa95532_0
  - httpx=0.28.1=py39haa95532_1
  - icu=75.1=he0c23c2_0
  - idna=3.11=py39haa95532_0
  - importlib-metadata=8.5.0=py39haa95532_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - ipykernel=6.30.1=py39haa95532_0
  - ipython=8.15.0=py39haa95532_0
  - ipython_pygments_lexers=1.1.1=py39haa95532_0
  - ipywidgets=8.1.7=py39haa95532_0
  - jedi=0.19.2=py39haa95532_0
  - jinja2=3.1.6=py39haa95532_0
  - json5=0.9.25=py39haa95532_0
  - jsonschema=4.25.0=py39haa95532_0
  - jsonschema-specifications=2023.7.1=py39haa95532_0
  - jupyter=1.1.1=py39haa95532_0
  - jupyter-lsp=2.2.5=py39haa95532_0
  - jupyter_client=8.6.3=py39haa95532_0
  - jupyter_console=6.6.3=py39haa95532_0
  - jupyter_core=5.8.1=py39haa95532_0
  - jupyter_events=0.12.0=py39haa95532_0
  - jupyter_server=2.16.0=py39haa95532_0
  - jupyter_server_terminals=0.5.3=py39haa95532_0
  - jupyterlab=4.4.7=py39haa95532_0
  - jupyterlab_pygments=0.3.0=py39haa95532_0
  - jupyterlab_server=2.28.0=py39haa95532_0
  - jupyterlab_widgets=3.0.15=py39haa95532_0
  - krb5=1.21.3=hdf4eb48_0
  - ld_impl_win-64=2.45=default_hfd38196_105
  - lerc=4.0.0=h6470a55_1
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libcurl=8.18.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libgcc-devel_win-64=15.2.0=hbb59886_116
  - libgfortran=15.2.0=h719f0c7_16
  - libgfortran5=15.2.0=h44d81a7_16
  - libglib=2.86.3=h0c9aed9_0
  - libgomp=15.2.0=h8ee18e1_16
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libpng=1.6.53=h7351971_0
  - libsodium=1.0.20=hc70643c_0
  - libssh2=1.11.1=h9aa295b_0
  - libstdcxx=15.2.0=hae5796f_16
  - libstdcxx-devel_win-64=15.2.0=h0a72980_116
  - libtiff=4.7.1=h8f73337_1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - m2-conda-epoch=20250515=0_x86_64
  - m2w64-sysroot_win-64=12.0.0.r4.gg4f2fc60ca=hd8ed1ab_10
  - markupsafe=3.0.2=py39h827c3e9_0
  - matplotlib-inline=0.1.7=py39haa95532_0
  - mingw-w64-ucrt-x86_64-crt-git=12.0.0.r4.gg4f2fc60ca=hd8ed1ab_10
  - mingw-w64-ucrt-x86_64-headers-git=12.0.0.r4.gg4f2fc60ca=hd8ed1ab_10
  - mingw-w64-ucrt-x86_64-windows-default-manifest=6.4=he206cdd_7
  - mingw-w64-ucrt-x86_64-winpthreads-git=12.0.0.r4.gg4f2fc60ca=hd8ed1ab_10
  - mistune=3.1.2=py39haa95532_0
  - mkl=2025.3.0=hac47afa_455
  - nbclient=0.10.2=py39haa95532_0
  - nbconvert=7.16.6=py39haa95532_0
  - nbconvert-core=7.16.6=py39haa95532_0
  - nbconvert-pandoc=7.16.6=py39haa95532_0
  - nbformat=5.10.4=py39haa95532_0
  - nest-asyncio=1.6.0=py39haa95532_0
  - notebook=7.4.5=py39haa95532_0
  - notebook-shim=0.2.4=py39haa95532_0
  - openssl=3.6.0=h725018a_0
  - overrides=7.4.0=py39haa95532_0
  - packaging=25.0=py39haa95532_1
  - pandoc=3.8=haa95532_0
  - pandocfilters=1.5.1=py39haa95532_0
  - parso=0.8.4=py39haa95532_0
  - pcre2=10.47=hd2b5f0e_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.3.7=py39haa95532_0
  - prometheus_client=0.21.1=py39haa95532_0
  - prompt-toolkit=3.0.52=py39haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py39h02ab6af_1
  - pure_eval=0.2.3=py39haa95532_0
  - pycparser=2.23=py39haa95532_0
  - pygments=2.19.1=py39haa95532_0
  - pysocks=1.7.1=py39haa95532_1
  - python=3.9.21=h8205438_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python-fastjsonschema=2.20.0=py39haa95532_0
  - python-json-logger=3.2.1=py39haa95532_0
  - pywin32=311=py39h885b0b7_0
  - pywinpty=2.0.15=py39h72d21ff_0
  - pyyaml=6.0.2=py39h827c3e9_0
  - pyzmq=27.1.0=py39h7149c55_0
  - qtconsole=5.7.0=py39haa95532_0
  - qtpy=2.4.3=py39haa95532_0
  - r-base=4.4.3=h347933c_7
  - r-base64enc=0.1_3=r44heceb674_1008
  - r-cli=3.6.5=r44hd8a2815_1
  - r-crayon=1.5.3=r44hc72bb7e_2
  - r-digest=0.6.39=r44hd8a2815_0
  - r-ellipsis=0.3.2=r44heceb674_4
  - r-evaluate=1.0.5=r44hc72bb7e_1
  - r-fansi=1.0.7=r44heceb674_0
  - r-fastmap=1.2.0=r44hd8a2815_2
  - r-glue=1.8.0=r44heceb674_1
  - r-htmltools=0.5.9=r44hd8a2815_0
  - r-irdisplay=1.1=r44hd8ed1ab_4
  - r-irkernel=1.3.2=r44h785f33e_3
  - r-jsonlite=2.0.0=r44heceb674_1
  - r-lifecycle=1.0.5=r44hc72bb7e_0
  - r-pbdzmq=0.3_14=r44h27c3720_1
  - r-pillar=1.11.1=r44hc72bb7e_0
  - r-repr=1.1.7=r44h785f33e_2
  - r-rlang=1.1.7=r44hd8a2815_0
  - r-utf8=1.2.6=r44heceb674_1
  - r-uuid=1.2_1=r44heceb674_1
  - r-vctrs=0.6.5=r44hd8a2815_2
  - referencing=0.30.2=py39haa95532_0
  - requests=2.32.5=py39haa95532_0
  - rfc3339-validator=0.1.4=py39haa95532_0
  - rfc3986-validator=0.1.1=py39haa95532_0
  - rpds-py=0.22.3=py39h636fa0f_0
  - send2trash=1.8.2=py39haa95532_1
  - setuptools=80.9.0=py39haa95532_0
  - six=1.17.0=py39haa95532_0
  - sniffio=1.3.0=py39haa95532_0
  - soupsieve=2.5=py39haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=py39haa95532_0
  - tbb=2022.3.0=h3155e25_2
  - terminado=0.18.1=py39haa95532_0
  - tinycss2=1.4.0=py39haa95532_0
  - tk=8.6.13=h2c6b04d_3
  - tktable=2.10=h7e9e0db_7
  - tomli=2.2.1=py39haa95532_0
  - tornado=6.5.1=py39h827c3e9_0
  - traitlets=5.14.3=py39haa95532_0
  - typing-extensions=4.15.0=py39haa95532_0
  - typing_extensions=4.15.0=py39haa95532_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.5.0=py39haa95532_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - wcwidth=0.2.13=py39haa95532_0
  - webencodings=0.5.1=py39haa95532_1
  - websocket-client=1.8.0=py39haa95532_0
  - wheel=0.45.1=py39haa95532_0
  - widgetsnbextension=4.0.14=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_1
  - winpty=0.4.3=4
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.21.0=py39haa95532_0
  - zstd=1.5.7=h534d264_6
prefix: C:\Users\user\miniconda3\envs\r_env
